import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { users, students, applications, documents, activityLogs } from "./schema";
import { count } from "drizzle-orm";
import bcrypt from "bcryptjs";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

async function seed() {
  const existingStudents = await db.select({ count: count() }).from(students);
  if (existingStudents[0].count > 0) {
    console.log(`Database already has ${existingStudents[0].count} students. Skipping seed.`);
    process.exit(0);
  }

  const existingUsers = await db.select({ count: count() }).from(users);
  if (existingUsers[0].count === 0) {
    const hashPassword = (pw: string) => bcrypt.hashSync(pw, 12);
    const now = new Date().toISOString();

    await db.insert(users).values([
      { id: "usr-admin", name: "Admin User", email: "admin@unilinkai.com", password: hashPassword("password"), role: "superadmin", createdAt: now },
      { id: "usr-agent", name: "Sarah Mitchell", email: "agent@unilinkai.com", password: hashPassword("password"), role: "agent", createdAt: now },
      { id: "usr-student", name: "Alex Johnson", email: "student@unilinkai.com", password: hashPassword("password"), role: "student", createdAt: now },
    ]);
    console.log("Seeded 3 auth users (admin/agent/student) with password: password");
  }

  await db.insert(students).values([
    { id: "stu-001", name: "Priya Sharma", email: "priya.sharma@email.com", phone: "+91 98765 43210", nationality: "Indian", passportNumber: "A1234567", educationLevel: "Master's", createdAt: "2024-01-15", dateOfBirth: "2001-05-12", gender: "Female", currentInstitution: "Delhi University", gpa: "8.5", yearOfCompletion: "2025", englishTestType: "IELTS", englishTestScore: "7.5", countryPreferences: "Australia,United Kingdom", coursePreferences: "Computer Science,Data Science", budget: "3000000", intakePreference: "Jul 2026", additionalNotes: "", title: "Ms", passportExpiry: "2030-05-12", countryOfResidence: "India", address: "12 MG Road, Sector 5", city: "Mumbai", emergencyContactName: "Raj Sharma", emergencyContactPhone: "+91 98765 43211", whatsappNumber: "+91 98765 43210", nativeLanguage: "Hindi", educationHistory: JSON.stringify([{ institution: "Delhi University", country: "India", degree: "B.Tech", fieldOfStudy: "Computer Science", startYear: "2019", endYear: "2023", gpa: "8.5", gradingScale: "cgpa-10", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "IELTS", overallScore: "7.5", listening: "7.0", reading: "8.0", writing: "6.5", speaking: "7.5", testDate: "2024-10-15", trfNumber: "IELTS123456" }]), standardizedTests: "[]", workExperience: JSON.stringify([{ employer: "TCS", jobTitle: "Software Engineer", industry: "IT", startDate: "2023-06-01", endDate: "", isCurrent: true, employmentType: "full-time", description: "Full stack development" }]), financialInfo: JSON.stringify({ budget: "3000000", budgetCurrency: "INR", fundingSource: "family", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "University of Melbourne", accommodationPreference: "on-campus", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-002", name: "Rohit Gupta", email: "rohit.gupta@email.com", phone: "+91 87654 32109", nationality: "Indian", passportNumber: "B2345678", educationLevel: "Postgraduate", createdAt: "2024-01-20", dateOfBirth: "1999-11-03", gender: "Male", currentInstitution: "IIT Bombay", gpa: "9.0", yearOfCompletion: "2024", englishTestType: "IELTS", englishTestScore: "7.0", countryPreferences: "Australia", coursePreferences: "Business & Management", budget: "4000000", intakePreference: "Feb 2026", title: "Mr", passportExpiry: "2029-11-03", countryOfResidence: "India", address: "45 Andheri Kurla Road", city: "Mumbai", emergencyContactName: "Sunita Gupta", emergencyContactPhone: "+91 87654 32110", whatsappNumber: "+91 87654 32109", nativeLanguage: "Hindi", educationHistory: JSON.stringify([{ institution: "IIT Bombay", country: "India", degree: "B.Tech", fieldOfStudy: "Mechanical Engineering", startYear: "2017", endYear: "2021", gpa: "9.0", gradingScale: "cgpa-10", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "IELTS", overallScore: "7.0", listening: "6.5", reading: "7.5", writing: "6.5", speaking: "7.0", testDate: "2024-08-20", trfNumber: "" }]), standardizedTests: "[]", workExperience: "[]", financialInfo: JSON.stringify({ budget: "4000000", budgetCurrency: "INR", fundingSource: "self", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "Deakin University", accommodationPreference: "off-campus", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-003", name: "Anita Singh", email: "anita.singh@email.com", phone: "+91 76543 21098", nationality: "Indian", passportNumber: "C3456789", educationLevel: "Undergraduate", createdAt: "2024-02-01", dateOfBirth: "2002-03-18", gender: "Female", currentInstitution: "Mumbai University", gpa: "7.8", yearOfCompletion: "2026", englishTestType: "TOEFL", englishTestScore: "95", countryPreferences: "Australia,New Zealand", coursePreferences: "Computer Science & IT", budget: "2500000", intakePreference: "Jul 2026", title: "Ms", passportExpiry: "2031-03-18", countryOfResidence: "India", address: "78 Bandra West", city: "Mumbai", emergencyContactName: "Vikram Singh", emergencyContactPhone: "+91 76543 21099", whatsappNumber: "+91 76543 21098", nativeLanguage: "Hindi", educationHistory: JSON.stringify([{ institution: "Mumbai University", country: "India", degree: "B.Sc", fieldOfStudy: "Computer Science", startYear: "2020", endYear: "2024", gpa: "7.8", gradingScale: "percentage", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "TOEFL", overallScore: "95", listening: "", reading: "", writing: "", speaking: "", testDate: "2024-06-10", trfNumber: "" }]), standardizedTests: "[]", workExperience: "[]", financialInfo: JSON.stringify({ budget: "2500000", budgetCurrency: "INR", fundingSource: "loan", bankStatementAvailable: false }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "", accommodationPreference: "homestay", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-004", name: "Kavya Nair", email: "kavya.nair@email.com", phone: "+91 65432 10987", nationality: "Indian", passportNumber: "D4567890", educationLevel: "Postgraduate", createdAt: "2024-02-10", dateOfBirth: "2000-08-25", gender: "Female", currentInstitution: "Kerala University", gpa: "8.2", yearOfCompletion: "2024", englishTestType: "IELTS", englishTestScore: "7.0", countryPreferences: "Australia", coursePreferences: "Computer Science & IT", budget: "3500000", intakePreference: "Feb 2026", title: "Ms", passportExpiry: "2030-08-25", countryOfResidence: "India", address: "12 Technopark Road", city: "Thiruvananthapuram", emergencyContactName: "Suresh Nair", emergencyContactPhone: "+91 65432 10988", whatsappNumber: "+91 65432 10987", nativeLanguage: "Malayalam", educationHistory: JSON.stringify([{ institution: "Kerala University", country: "India", degree: "BCA", fieldOfStudy: "Computer Applications", startYear: "2018", endYear: "2021", gpa: "8.2", gradingScale: "cgpa-10", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "IELTS", overallScore: "7.0", listening: "6.5", reading: "7.0", writing: "6.5", speaking: "7.0", testDate: "2024-07-05", trfNumber: "" }]), standardizedTests: "[]", workExperience: JSON.stringify([{ employer: "Wipro", jobTitle: "Data Analyst", industry: "IT", startDate: "2021-08-01", endDate: "2024-01-31", isCurrent: false, employmentType: "full-time", description: "Data analysis and visualization" }]), financialInfo: JSON.stringify({ budget: "3500000", budgetCurrency: "INR", fundingSource: "family", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "UTS", accommodationPreference: "on-campus", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-005", name: "Amit Kumar", email: "amit.kumar@email.com", phone: "+91 54321 09876", nationality: "Indian", passportNumber: "E5678901", educationLevel: "Postgraduate", createdAt: "2024-02-15", dateOfBirth: "1997-01-30", gender: "Male", currentInstitution: "IIT Delhi", gpa: "9.2", yearOfCompletion: "2023", englishTestType: "IELTS", englishTestScore: "8.0", countryPreferences: "Australia,United Kingdom", coursePreferences: "Engineering", budget: "5000000", intakePreference: "Jul 2026", additionalNotes: "Research focus on AI", title: "Mr", passportExpiry: "2028-01-30", countryOfResidence: "India", address: "56 Hauz Khas", city: "New Delhi", emergencyContactName: "Meena Kumar", emergencyContactPhone: "+91 54321 09877", whatsappNumber: "+91 54321 09876", nativeLanguage: "Hindi", educationHistory: JSON.stringify([{ institution: "IIT Delhi", country: "India", degree: "M.Tech", fieldOfStudy: "Artificial Intelligence", startYear: "2021", endYear: "2023", gpa: "9.2", gradingScale: "cgpa-10", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "IELTS", overallScore: "8.0", listening: "7.5", reading: "8.5", writing: "7.5", speaking: "8.0", testDate: "2024-05-20", trfNumber: "IELTS789012" }]), standardizedTests: "[]", workExperience: "[]", financialInfo: JSON.stringify({ budget: "5000000", budgetCurrency: "INR", fundingSource: "scholarship", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "Monash University", accommodationPreference: "no-preference", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-006", name: "Sarah Johnson", email: "sarah.j@email.com", phone: "+44 7911 123456", nationality: "British", passportNumber: "F6789012", educationLevel: "Postgraduate", createdAt: "2024-03-01", dateOfBirth: "1999-07-14", gender: "Female", currentInstitution: "University of Manchester", gpa: "3.8", yearOfCompletion: "2024", englishTestType: "None", englishTestScore: "", countryPreferences: "Australia", coursePreferences: "Finance & Economics", budget: "3000000", intakePreference: "Feb 2026", title: "Ms", passportExpiry: "2029-07-14", countryOfResidence: "United Kingdom", address: "8 Oxford Road", city: "Manchester", emergencyContactName: "Tom Johnson", emergencyContactPhone: "+44 7911 123457", whatsappNumber: "+44 7911 123456", nativeLanguage: "English", educationHistory: JSON.stringify([{ institution: "University of Manchester", country: "United Kingdom", degree: "BSc", fieldOfStudy: "Economics", startYear: "2017", endYear: "2020", gpa: "3.8", gradingScale: "gpa-4", stillEnrolled: false }]), englishTestDetails: "[]", standardizedTests: "[]", workExperience: JSON.stringify([{ employer: "Deloitte", jobTitle: "Junior Analyst", industry: "Finance", startDate: "2020-09-01", endDate: "2024-02-28", isCurrent: false, employmentType: "full-time", description: "Financial analysis and consulting" }]), financialInfo: JSON.stringify({ budget: "3000000", budgetCurrency: "GBP", fundingSource: "self", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "University of Sydney", accommodationPreference: "off-campus", postStudyWorkInterest: "no", consentGiven: "yes", status: "complete" },
    { id: "stu-007", name: "Wei Zhang", email: "wei.zhang@email.com", phone: "+86 138 1234 5678", nationality: "Chinese", passportNumber: "G7890123", educationLevel: "Undergraduate", createdAt: "2024-03-05", dateOfBirth: "2001-09-22", gender: "Male", currentInstitution: "Peking University", gpa: "3.5", yearOfCompletion: "2025", englishTestType: "IELTS", englishTestScore: "6.5", countryPreferences: "Australia,New Zealand", coursePreferences: "Engineering", budget: "2800000", intakePreference: "Jul 2026", title: "Mr", passportExpiry: "2030-09-22", countryOfResidence: "China", address: "234 Zhongguancun", city: "Beijing", emergencyContactName: "Li Zhang", emergencyContactPhone: "+86 138 1234 5679", whatsappNumber: "+86 138 1234 5678", nativeLanguage: "Mandarin", educationHistory: JSON.stringify([{ institution: "Peking University", country: "China", degree: "BEng", fieldOfStudy: "Civil Engineering", startYear: "2019", endYear: "2023", gpa: "3.5", gradingScale: "gpa-4", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "IELTS", overallScore: "6.5", listening: "6.0", reading: "7.0", writing: "6.0", speaking: "6.5", testDate: "2024-04-15", trfNumber: "" }]), standardizedTests: "[]", workExperience: "[]", financialInfo: JSON.stringify({ budget: "2800000", budgetCurrency: "INR", fundingSource: "family", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "", accommodationPreference: "on-campus", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-008", name: "Fatima Al-Rashid", email: "fatima.r@email.com", phone: "+971 50 123 4567", nationality: "Emirati", passportNumber: "H8901234", educationLevel: "Postgraduate", createdAt: "2024-03-10", dateOfBirth: "2000-04-08", gender: "Female", currentInstitution: "American University of Sharjah", gpa: "3.6", yearOfCompletion: "2024", englishTestType: "IELTS", englishTestScore: "6.5", countryPreferences: "United Kingdom", coursePreferences: "Health Sciences", budget: "6000000", intakePreference: "Oct 2026", title: "Ms", passportExpiry: "2029-04-08", countryOfResidence: "United Arab Emirates", address: "12 Al Nahda Street", city: "Dubai", emergencyContactName: "Ahmed Al-Rashid", emergencyContactPhone: "+971 50 123 4568", whatsappNumber: "+971 50 123 4567", nativeLanguage: "Arabic", educationHistory: JSON.stringify([{ institution: "American University of Sharjah", country: "United Arab Emirates", degree: "BSc", fieldOfStudy: "Public Health", startYear: "2018", endYear: "2022", gpa: "3.6", gradingScale: "gpa-4", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "IELTS", overallScore: "6.5", listening: "6.0", reading: "7.0", writing: "6.0", speaking: "6.5", testDate: "2024-03-01", trfNumber: "" }]), standardizedTests: "[]", workExperience: "[]", financialInfo: JSON.stringify({ budget: "6000000", budgetCurrency: "AED", fundingSource: "family", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "University of Queensland", accommodationPreference: "on-campus", postStudyWorkInterest: "no", consentGiven: "yes", status: "complete" },
    { id: "stu-009", name: "Carlos Mendez", email: "carlos.m@email.com", phone: "+52 55 1234 5678", nationality: "Mexican", passportNumber: "I9012345", educationLevel: "Undergraduate", createdAt: "2024-03-15", dateOfBirth: "2002-12-01", gender: "Male", currentInstitution: "UNAM", gpa: "8.0", yearOfCompletion: "2026", englishTestType: "TOEFL", englishTestScore: "88", countryPreferences: "Canada,United States", coursePreferences: "Business & Management", budget: "2000000", intakePreference: "Feb 2026", title: "Mr", passportExpiry: "2031-12-01", countryOfResidence: "Mexico", address: "45 Reforma Avenue", city: "Mexico City", emergencyContactName: "Maria Mendez", emergencyContactPhone: "+52 55 1234 5679", whatsappNumber: "+52 55 1234 5678", nativeLanguage: "Spanish", educationHistory: JSON.stringify([{ institution: "UNAM", country: "Mexico", degree: "Licenciatura", fieldOfStudy: "Business Administration", startYear: "2020", endYear: "2024", gpa: "8.0", gradingScale: "percentage", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "TOEFL", overallScore: "88", listening: "", reading: "", writing: "", speaking: "", testDate: "2024-02-15", trfNumber: "" }]), standardizedTests: "[]", workExperience: "[]", financialInfo: JSON.stringify({ budget: "2000000", budgetCurrency: "INR", fundingSource: "self", bankStatementAvailable: false }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "", accommodationPreference: "no-preference", postStudyWorkInterest: "undecided", consentGiven: "yes", status: "complete" },
    { id: "stu-010", name: "Aisha Patel", email: "aisha.p@email.com", phone: "+91 43210 98765", nationality: "Indian", passportNumber: "J0123456", educationLevel: "Postgraduate", createdAt: "2024-03-20", dateOfBirth: "2000-06-17", gender: "Female", currentInstitution: "Ahmedabad University", gpa: "8.8", yearOfCompletion: "2024", englishTestType: "IELTS", englishTestScore: "7.5", countryPreferences: "Australia,United Kingdom", coursePreferences: "Computer Science & IT", budget: "4000000", intakePreference: "Jul 2026", title: "Ms", passportExpiry: "2030-06-17", countryOfResidence: "India", address: "78 CG Road", city: "Ahmedabad", emergencyContactName: "Kiran Patel", emergencyContactPhone: "+91 43210 98766", whatsappNumber: "+91 43210 98765", nativeLanguage: "Gujarati", educationHistory: JSON.stringify([{ institution: "Ahmedabad University", country: "India", degree: "BCA", fieldOfStudy: "Computer Applications", startYear: "2018", endYear: "2021", gpa: "8.8", gradingScale: "cgpa-10", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "IELTS", overallScore: "7.5", listening: "7.0", reading: "8.0", writing: "7.0", speaking: "7.5", testDate: "2024-09-10", trfNumber: "IELTS345678" }]), standardizedTests: "[]", workExperience: JSON.stringify([{ employer: "Infosys", jobTitle: "Software Developer", industry: "IT", startDate: "2021-07-01", endDate: "", isCurrent: true, employmentType: "full-time", description: "Full stack development and cloud architecture" }]), financialInfo: JSON.stringify({ budget: "4000000", budgetCurrency: "INR", fundingSource: "self", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "University of Adelaide", accommodationPreference: "on-campus", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-011", name: "David Kim", email: "david.kim@email.com", phone: "+82 10 1234 5678", nationality: "South Korean", passportNumber: "K1234567", educationLevel: "Postgraduate", createdAt: "2024-04-01", dateOfBirth: "1996-10-05", gender: "Male", currentInstitution: "Seoul National University", gpa: "3.9", yearOfCompletion: "2023", englishTestType: "TOEFL", englishTestScore: "102", countryPreferences: "Australia,United Kingdom", coursePreferences: "Computer Science & IT,Engineering", budget: "5000000", intakePreference: "Feb 2026", additionalNotes: "AI research background", title: "Mr", passportExpiry: "2028-10-05", countryOfResidence: "South Korea", address: "100 Gwanak-ro", city: "Seoul", emergencyContactName: "Ji-Hye Kim", emergencyContactPhone: "+82 10 1234 5679", whatsappNumber: "+82 10 1234 5678", nativeLanguage: "Korean", educationHistory: JSON.stringify([{ institution: "Seoul National University", country: "South Korea", degree: "MS", fieldOfStudy: "Computer Science", startYear: "2019", endYear: "2021", gpa: "3.9", gradingScale: "gpa-4", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "TOEFL", overallScore: "102", listening: "", reading: "", writing: "", speaking: "", testDate: "2024-01-20", trfNumber: "" }]), standardizedTests: JSON.stringify([{ testType: "GRE", score: "325", breakdown: "V160 Q165 AWA4.5", testDate: "2023-12-10" }]), workExperience: JSON.stringify([{ employer: "Samsung SDS", jobTitle: "AI Research Engineer", industry: "IT", startDate: "2021-03-01", endDate: "", isCurrent: true, employmentType: "full-time", description: "Machine learning model development" }]), financialInfo: JSON.stringify({ budget: "5000000", budgetCurrency: "KRW", fundingSource: "employer", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "Monash University", accommodationPreference: "off-campus", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
    { id: "stu-012", name: "Neha Verma", email: "neha.v@email.com", phone: "+91 32109 87654", nationality: "Indian", passportNumber: "L2345678", educationLevel: "Undergraduate", createdAt: "2024-04-05", dateOfBirth: "2003-02-28", gender: "Female", currentInstitution: "Lucknow University", gpa: "7.5", yearOfCompletion: "2026", englishTestType: "PTE", englishTestScore: "62", countryPreferences: "New Zealand,Australia", coursePreferences: "Health Sciences", budget: "2000000", intakePreference: "Oct 2026", title: "Ms", passportExpiry: "2032-02-28", countryOfResidence: "India", address: "34 Hazratganj", city: "Lucknow", emergencyContactName: "Deepak Verma", emergencyContactPhone: "+91 32109 87655", whatsappNumber: "+91 32109 87654", nativeLanguage: "Hindi", educationHistory: JSON.stringify([{ institution: "Lucknow University", country: "India", degree: "BSc", fieldOfStudy: "Nursing", startYear: "2021", endYear: "2024", gpa: "7.5", gradingScale: "percentage", stillEnrolled: false }]), englishTestDetails: JSON.stringify([{ testType: "PTE", overallScore: "62", listening: "", reading: "", writing: "", speaking: "", testDate: "2024-03-15", trfNumber: "" }]), standardizedTests: "[]", workExperience: JSON.stringify([{ employer: "Medanta Hospital", jobTitle: "Nurse", industry: "Healthcare", startDate: "2024-01-01", endDate: "", isCurrent: true, employmentType: "full-time", description: "Patient care in general ward" }]), financialInfo: JSON.stringify({ budget: "2000000", budgetCurrency: "INR", fundingSource: "family", bankStatementAvailable: true }), visaHistory: JSON.stringify({ hasVisaRefusals: false, visaRefusalDetails: "", hasStudiedAbroad: false, studyAbroadDetails: "", currentVisaStatus: "None" }), preferredInstitutions: "Curtin University", accommodationPreference: "homestay", postStudyWorkInterest: "yes", consentGiven: "yes", status: "complete" },
  ]);

  await db.insert(applications).values([
    { id: "app-001", studentId: "stu-001", university: "University of Melbourne", course: "Master of Computer Science", stage: "visa_processing", status: "active", accommodation: "yes", insurance: "yes", submittedAt: "2024-01-20", updatedAt: "2024-03-15" },
    { id: "app-002", studentId: "stu-002", university: "Deakin University", course: "MBA", stage: "offer_received", status: "active", accommodation: "yes", insurance: "no", submittedAt: "2024-01-25", updatedAt: "2024-03-10" },
    { id: "app-003", studentId: "stu-003", university: "RMIT University", course: "Bachelor of IT", stage: "application_submitted", status: "active", accommodation: "no", insurance: "yes", submittedAt: "2024-02-05", updatedAt: "2024-02-05" },
    { id: "app-004", studentId: "stu-004", university: "UTS", course: "Master of Data Science", stage: "visa_approved", status: "completed", accommodation: "yes", insurance: "yes", submittedAt: "2024-02-15", updatedAt: "2024-04-01" },
    { id: "app-005", studentId: "stu-005", university: "Monash University", course: "PhD in Engineering", stage: "visa_processing", status: "active", accommodation: "no", insurance: "yes", submittedAt: "2024-02-20", updatedAt: "2024-03-20" },
    { id: "app-006", studentId: "stu-006", university: "University of Sydney", course: "Master of Finance", stage: "offer_received", status: "active", accommodation: "yes", insurance: "no", submittedAt: "2024-03-05", updatedAt: "2024-03-25" },
    { id: "app-007", studentId: "stu-007", university: "UNSW", course: "Bachelor of Engineering", stage: "application_submitted", status: "active", accommodation: "yes", insurance: "na", submittedAt: "2024-03-10", updatedAt: "2024-03-10" },
    { id: "app-008", studentId: "stu-008", university: "University of Queensland", course: "Master of Public Health", stage: "lead", status: "active", accommodation: "no", insurance: "na", submittedAt: "2024-03-15", updatedAt: "2024-03-15" },
    { id: "app-009", studentId: "stu-009", university: "Macquarie University", course: "Bachelor of Business", stage: "lead", status: "active", accommodation: null, insurance: null, submittedAt: "2024-03-20", updatedAt: "2024-03-20" },
    { id: "app-010", studentId: "stu-010", university: "University of Adelaide", course: "Master of AI", stage: "visa_approved", status: "completed", accommodation: "yes", insurance: "yes", submittedAt: "2024-03-25", updatedAt: "2024-04-10" },
    { id: "app-011", studentId: "stu-011", university: "Flinders University", course: "PhD in Computer Science", stage: "offer_received", status: "active", accommodation: "no", insurance: "no", submittedAt: "2024-04-05", updatedAt: "2024-04-15" },
    { id: "app-012", studentId: "stu-012", university: "Curtin University", course: "Master of Nursing", stage: "application_submitted", status: "active", accommodation: "yes", insurance: "na", submittedAt: "2024-04-10", updatedAt: "2024-04-10" },
    { id: "app-013", studentId: "stu-001", university: "RMIT University", course: "Master of IT", stage: "lead", status: "active", accommodation: "no", insurance: "na", submittedAt: "2024-04-01", updatedAt: "2024-04-01" },
    { id: "app-014", studentId: "stu-003", university: "Swinburne University", course: "Bachelor of Design", stage: "visa_processing", status: "active", accommodation: "yes", insurance: "yes", submittedAt: "2024-02-10", updatedAt: "2024-03-28" },
    { id: "app-015", studentId: "stu-005", university: "La Trobe University", course: "Master of Data Science", stage: "visa_approved", status: "completed", accommodation: "no", insurance: "yes", submittedAt: "2024-01-15", updatedAt: "2024-03-01" },
  ]);

  await db.insert(documents).values([
    { id: "doc-001", studentId: "stu-001", applicationId: "app-001", type: "passport", fileName: "priya_passport.pdf", uploadedAt: "2024-01-16", verified: true },
    { id: "doc-002", studentId: "stu-001", applicationId: "app-001", type: "financial", fileName: "priya_bank_statement.pdf", uploadedAt: "2024-01-17", verified: true },
    { id: "doc-003", studentId: "stu-001", applicationId: "app-001", type: "scores", fileName: "priya_ielts_score.pdf", uploadedAt: "2024-01-18", verified: true },
    { id: "doc-004", studentId: "stu-002", applicationId: "app-002", type: "passport", fileName: "rohit_passport.pdf", uploadedAt: "2024-01-26", verified: true },
    { id: "doc-005", studentId: "stu-002", applicationId: "app-002", type: "financial", fileName: "rohit_sponsor_letter.pdf", uploadedAt: "2024-01-27", verified: false },
    { id: "doc-006", studentId: "stu-003", applicationId: "app-003", type: "passport", fileName: "anita_passport.pdf", uploadedAt: "2024-02-06", verified: true },
    { id: "doc-007", studentId: "stu-004", applicationId: "app-004", type: "passport", fileName: "kavya_passport.pdf", uploadedAt: "2024-02-16", verified: true },
    { id: "doc-008", studentId: "stu-004", applicationId: "app-004", type: "financial", fileName: "kavya_bank_statement.pdf", uploadedAt: "2024-02-17", verified: true },
    { id: "doc-009", studentId: "stu-004", applicationId: "app-004", type: "scores", fileName: "kavya_gre_score.pdf", uploadedAt: "2024-02-18", verified: true },
    { id: "doc-010", studentId: "stu-005", applicationId: "app-005", type: "passport", fileName: "amit_passport.pdf", uploadedAt: "2024-02-21", verified: true },
    { id: "doc-011", studentId: "stu-008", applicationId: "app-008", type: "passport", fileName: "fatima_passport.pdf", uploadedAt: "2024-03-16", verified: false },
    { id: "doc-012", studentId: "stu-010", applicationId: "app-010", type: "passport", fileName: "aisha_passport.pdf", uploadedAt: "2024-03-26", verified: true },
    { id: "doc-013", studentId: "stu-010", applicationId: "app-010", type: "financial", fileName: "aisha_scholarship_letter.pdf", uploadedAt: "2024-03-27", verified: true },
  ]);

  await db.insert(activityLogs).values([
    { id: "act-001", studentId: "stu-001", applicationId: "app-001", action: "stage_changed", note: "Moved to visa processing", performedBy: "Sarah Mitchell", createdAt: "2024-03-15" },
    { id: "act-002", studentId: "stu-002", applicationId: "app-002", action: "document_uploaded", note: "Financial sponsor letter uploaded", performedBy: "Agent", createdAt: "2024-01-27" },
    { id: "act-003", studentId: "stu-003", applicationId: "app-003", action: "application_created", note: "Application submitted to RMIT", performedBy: "Sarah Mitchell", createdAt: "2024-02-05" },
    { id: "act-004", studentId: "stu-004", applicationId: "app-004", action: "stage_changed", note: "Visa approved! Student can proceed.", performedBy: "Sarah Mitchell", createdAt: "2024-04-01" },
    { id: "act-005", studentId: "stu-005", applicationId: "app-005", action: "stage_changed", note: "Moved to visa processing", performedBy: "Sarah Mitchell", createdAt: "2024-03-20" },
    { id: "act-006", studentId: "stu-008", applicationId: "app-008", action: "document_requested", note: "Requested passport copy from student", performedBy: "Sarah Mitchell", createdAt: "2024-03-16" },
    { id: "act-007", studentId: "stu-010", applicationId: "app-010", action: "stage_changed", note: "Visa approved!", performedBy: "Sarah Mitchell", createdAt: "2024-04-10" },
    { id: "act-008", studentId: "stu-011", applicationId: "app-011", action: "offer_received", note: "Offer letter received from Flinders", performedBy: "System", createdAt: "2024-04-15" },
  ]);

  console.log(`Seeded 12 students, 15 applications, 13 documents, 8 activities.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
